# Python tests are run on every push to the dev branch and pull request.
name: test-python

on:
  push:
    branches: ["dev"]
  pull_request:
    branches: ["dev"]

concurrency:
  group: test-${{ github.head_ref }}
  cancel-in-progress: true

env:
  PYTHONUNBUFFERED: "1"
  FORCE_COLOR: "1"

jobs:
  run:
    name: ${{ matrix.project.name }} tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        project:
          - { name: "algorithm-client", path: "./algorithm-client/package" }
          - {
              name: "fill-remove",
              path: "./algorithm-client/algorithms/fill-remove",
            }

    # starting a temporary PostgreSQL container
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_DB: ${{secrets.POSTGRES_DB}}
          POSTGRES_USER: ${{secrets.CI_USER}}
          POSTGRES_PASSWORD: ${{secrets.CI_PASSWORD}}
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    defaults:
      run:
        working-directory: ${{ matrix.project.path }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Install Hatch
        run: pip install --upgrade hatch

      - name: Fix virtualenv compatibility
        run: |
          python -m pip install --upgrade pip
          pip install "virtualenv==20.26.6"  

    # adding flyway & migration steps
      # waiting for PostgreSQL
      - name: Wait for PostgreSQL readiness
        env:
          POSTGRES_USER: ${{secrets.CI_USER}}
        run: |
          for i in {1..10}; do 
            if docker exec $(docker ps -q --filter name=postgres) pg_isready -h localhost -p 5432 -U "$POSTGRES_USER"; then
              echo "PostgreSQL is ready."
              break
            fi
            echo "Waiting for PostgreSQL... attempt $i"
            sleep 5
          done
      # installing flyway
      - name: Install Flyway
        run: |
          FLYWAY_VERSION=10.10.0
          curl -L https://download.red-gate.com/maven/release/com/redgate/flyway/flyway-commandline/$FLYWAY_VERSION/flyway-commandline-$FLYWAY_VERSION-linux-x64.tar.gz | tar -xz
          sudo mv flyway-$FLYWAY_VERSION /usr/local/share/flyway
          sudo ln -s /usr/local/share/flyway/flyway /usr/local/bin/flyway
      # running flyway migrations
      - name: Run Flyway Migrations
        env:
          FLYWAY_URL: jdbc:postgresql://localhost:5432/${{secrets.POSTGRES_DB}}
          FLYWAY_USER: ${{secrets.CI_USER}}
          FLYWAY_PASSWORD: ${{secrets.CI_PASSWORD}}
        run: flyway migrate

      - name: Run static analysis
        run: hatch fmt --check

      - name: Run tests
        # exposing DB credentials to the python runtime environment 
        env:
          DB_HOST: localhost
          DB_USER: ${{secrets.CI_USER}}
          DB_PASS: ${{secrets.CI_PASSWORD}}
          DB_NAME: ${{secrets.POSTGRES_DB}}
          # including all pg variables
          PGHOST: localhost
          PGUSER: ${{secrets.CI_USER}}
          PGPASSWORD: ${{secrets.CI_PASSWORD}}
          PGDATABASE: ${{secrets.POSTGRES_DB}}
          PGPORT: 5432
        run: hatch test --python 3.8 --cover --randomize --parallel --retries 2 --retry-delay 1
